[general]
hide_overlay_in_screen_share = false
passthrough_unbounded_keys = true
passthrough_unbounded_keys_blacklist = []

[hotkeys]
# "Shift+f" = "recursive_grid"
"Ctrl+Space" = "recursive_grid --action left_click"
"F20" = "scroll"

[action.key_bindings]
left_click = "Return"
right_click = "Cmd+L"
middle_click = "Shift+M"
mouse_down = "Shift+D"
mouse_up = "Shift+U"
move_mouse_up = "Up"
move_mouse_down = "Down"
move_mouse_left = "Left"
move_mouse_right = "Right"

[hints]
# enable = false
font_size = 10
ignore_clickable_check = true

[grid]
characters = "asdfvbhjkl;"
sublayer_keys = "asdfhjkl;"
prewarm_enabled = true
label_color = "#000000"


[recursive_grid]
# # 3x3 grid
# enabled = true
# grid_cols = 3
# grid_rows = 3
# keys = "aksh ldjf"
reset_key = "'"
min_size_width = 10
min_size_height = 10
max_depth = 2

auto_exit_actions = ["left_click", "right_click"]
# # If you also want right click, add another hotkey like:
# # "Shift+r" = "recursive_grid --action right_click"

grid_cols = 5
grid_rows = 5
# keys = "asdfghjklqwertyuiopzxcvbn"
keys = "qwertyuiopasdfghjklzxcvbn"

# keys = "qwertasdfgcv nmyuiophjkl;"

# y9san9's keys
# keys = "asdfghjklqwertyuiopzxcvbnm,./;"
#
# # keys = "aksh ldjf"  # contains Space, so one cell is blank and selected with Space
# keys = "akshldjfg"
#
# reset_key = ","

[recursive_grid.ui]
font_size = 15

sub_key_preview = true                     # Draw miniature key grid inside each cell
sub_key_preview_font_size = 8
sub_key_preview_text_color_light = "#FFFF0000"
sub_key_preview_text_color_dark = "#FFFF0000"

line_color_light = "#FFFF0000"
text_color_light = "#FFFF0000"
highlight_color_light = "#22FFFFFF"

line_color_dark = "#FFFF0000"
text_color_dark = "#FFFF0000"
highlight_color_dark = "#22FFFFFF"

[mode_indicator.scroll]
enabled = true
text = "Scrolllll"

[mode_indicator.hints]
enabled = false
text = "Hints"

[mode_indicator.grid]
enabled = false
text = "Grid"

[mode_indicator.recursive_grid]
enabled = false
text = "Recursive Grid"
[smooth_cursor]
move_mouse_enabled = true
steps = 10                                  # Number of intermediate positions
delay = 1    

[systray]
enabled = false
