[general]
hide_overlay_in_screen_share = true
passthrough_unbounded_keys = true
should_exit_after_passthrough = true

mode_exit_keys = ["escape", "Ctrl+C"]

[hotkeys]
# disable defaults
"Cmd+Shift+Space" = "__disabled__"
"Cmd+Shift+G" = "__disabled__"
"Cmd+Shift+C" = "__disabled__"
"Cmd+Shift+S" = "__disabled__"

"Ctrl+K" = ["action left_click", "idle"]
"Ctrl+S" = "scroll"
"Ctrl+J" = ["recursive_grid --action left_click"]
"Shift+Space" = ["recursive_grid --action left_click --repeat"]

# "Return" = ["action left_click", "exec sleep 0.5", "hints"]
"Ctrl+R" = "action right_click"
"Ctrl+M" = "action middle_click"

"Option+Escape" = "recursive_grid --cursor-selection-mode hold"
"Option+Cmd+Space" = "action right_click"

# [action.key_bindings]
# left_click = "Return"
# right_click = "Ctrl+R"
# middle_click = "Ctrl+M"

# These keys dont have to be here, i didn't want to install another program to run these
"Cmd+Alt+Shift+Ctrl+F" = "exec open -a \"Finder\""
"Cmd+Alt+Shift+Ctrl+B" = "exec open -a \"Helium\""
# "Cmd+Alt+Shift+Ctrl+B" = "exec open -a \"Safari Technology Preview\""
"Cmd+Alt+Shift+Ctrl+T" = "exec open -a \"Kitty\""
"Cmd+Alt+Shift+Ctrl+N" = "exec open -a \"Notes\""
# "Cmd+Alt+Shift+Ctrl+R" = "exec open -a \"Reminders\""
# "Cmd+Alt+Shift+Ctrl+M" = "exec open -a \"Mail\""
# "Cmd+Alt+Shift+Ctrl+C" = "exec open -a \"Calendar\""
# "Cmd+Alt+Shift+Ctrl+W" = "exec open -a \"WhatsApp\""
"Cmd+Alt+Shift+Ctrl+P" = "exec open -a \"1Passwords\""
"Cmd+Alt+Shift+Ctrl+S" = "exec open -a \"System Settings\""
"Cmd+Alt+Shift+Ctrl+A" = "exec open -a \"Activity Monitor\""

# "Alt+Shift+1" = "exec move-to-space 1"
# "Alt+Shift+2" = "exec move-to-space 2"
# "Alt+Shift+3" = "exec move-to-space 3"
# "Alt+Shift+4" = "exec move-to-space 4"
# "Alt+Shift+5" = "exec move-to-space 5"
# "Alt+Shift+6" = "exec move-to-space 6"
# "Alt+Shift+7" = "exec move-to-space 7"
# "Alt+Shift+8" = "exec move-to-space 8"
# "Alt+Shift+9" = "exec move-to-space 9"
[recursive_grid]
min_size_height = 1
min_size_width = 1
max_depth = 10
auto_exit_actions = []
# min_size_width = 15
# min_size_height = 15
# max_depth = 3
reset_key = ","
#                                                               
# 5x5 greed
#speed_run
# keys = "qweasdzxcrfvtgbyhnujmikol"
# keys = "qwertasdfghjklnzxcvbyuiop"
#for memory
keys = "qwertyuiopasdfghjklnzxcvb"
grid_cols = 5
grid_rows = 5
# was
# keys = "qwertyuiopasdfghjklzxcvbn"

# y9san9's keys
# keys = "asdfghjklqwertyuiopzxcvbnm,./;"
#                                                               
# # 5x3 greed
# grid_cols = 5
# grid_rows = 3
# keys = "ertyudfghjcvbnm"
#                                                               

[recursive_grid.ui]
sub_key_preview = true
font_size = 16
sub_key_preview_font_size = 12
sub_key_preview_text_color_light = "#FFFF0000"
sub_key_preview_text_color_dark = "#FFFF0000"

line_color_light = "#FFFF0000"
text_color_light = "#FFFF0000"
highlight_color_light = "#22FFFFFF"

line_color_dark = "#FFFF0000"
# text_color_dark = "#FFFF0000"
highlight_color_dark = "#22FFFFFF"

label_background = true
label_background_color_light = "#FFAAEEFF"
label_background_color_dark = "#FF003554"
label_background_padding_x = -1
label_background_padding_y = -1
label_background_border_radius = -1
label_background_border_width = 1


[scroll]
stay_active_in_background = true

## ============================================================================
# Mode Indicator
# ============================================================================
[mode_indicator.ui]
font_family = "JetBrainsMonoNLNFP-Bold"
font_size = 4
border_radius = 50
border_color_light = "#00000000"
border_color_dark = "#00000000"
border_width = 0
padding_x = -1
padding_y = -1
indicator_x_offset = 10
indicator_y_offset = -20

[mode_indicator.scroll]
enabled = true
text = " "
background_color_light = "#FF00CF55"
background_color_dark = "#FF00CF55"

[mode_indicator.recursive_grid]
enabled = true
text = " "
background_color_light = "#FFFFCF55"
background_color_dark = "#FFFFCF55"

[smooth_cursor]
move_mouse_enabled = true
steps = 100
max_duration = 200
duration_per_pixel = 0.01

[systray]
enabled = false
