return {
  -- We don’t need an external plugin here, just add our command + keymap
  {
    "nvim-lua/plenary.nvim", -- dependency to keep it consistent (already in LazyVim)
    config = function()
      -- Define :GenCommitMsg command
      vim.api.nvim_create_user_command("GenCommitMsg", function()
        local output = vim.fn.systemlist("~/bin/gen-commit-msg")
        if vim.v.shell_error ~= 0 then
          vim.notify(table.concat(output, "\n"), vim.log.levels.ERROR)
          return
        end
        if vim.bo.filetype == "gitcommit" then
          vim.api.nvim_buf_set_lines(0, 0, 1, false, { output[1] })
        else
          vim.api.nvim_put(output, "l", true, true)
        end
        vim.notify("Commit message generated by my LLM")
      end, {})

      -- Keymap <leader>gc to trigger generation
      vim.keymap.set("n", "<leader>gc", ":GenCommitMsg<CR>", {
        silent = true,
        desc = "Generate commit message via DeepSeek",
      })
    end,
  },
}
