include theme.conf
include tabs.conf
include font-size.conf
allow_remote_control yes
listen_on unix:/tmp/mykitty
map cmd+equal launch --type=background --allow-remote-control /Users/marv/bin/kitty-font-size increase
map cmd+plus launch --type=background --allow-remote-control /Users/marv/bin/kitty-font-size increase
map cmd+kp_add launch --type=background --allow-remote-control /Users/marv/bin/kitty-font-size increase
map cmd+minus launch --type=background --allow-remote-control /Users/marv/bin/kitty-font-size decrease
map cmd+kp_subtract launch --type=background --allow-remote-control /Users/marv/bin/kitty-font-size decrease
map cmd+0 launch --type=background --allow-remote-control /Users/marv/bin/kitty-font-size reset
